In [76]:
import torch.nn as nn
import numpy as np
import torch

x = nn.Embedding(10,4)
input = np.full((1,20),1)
input_t = torch.tensor(input)
y = x(input_t)

In [77]:
input

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [78]:
input_t.shape

torch.Size([1, 20])

In [79]:
y

# 1 2 3 4 5 6
# 4 5 6 1 2 3
# 4 10 18 4 10 18

tensor([[[ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302],
         [ 0.4697,  0.0343, -0.7851, -1.4302]]], grad_fn=<EmbeddingBackward>)

In [80]:
m = nn.Softmax(dim=-1)
output = m(torch.random)

RuntimeError: "softmax_lastdim_kernel_impl" not implemented for 'Long'

In [ ]:
input

tensor([[-1.0617,  0.9130,  0.7148],
        [ 1.9936, -0.0333, -0.1742]])

In [ ]:
output

tensor([[0.0709, 0.5105, 0.4187],
        [0.8025, 0.1057, 0.0918]])

In [48]:
import networkx as nx

G = nx.MultiDiGraph()

In [49]:
G.add_edge("u1","u2")
G.add_edge("u3","u4")

0

In [50]:
G.edges

OutMultiEdgeView([('u1', 'u2', 0), ('u3', 'u4', 0)])

In [19]:
# A = G.adjacency()
A = nx.adjacency_matrix(G)

In [55]:
G.nodes

NodeView(('u1', 'u2', 'u3', 'u4'))

In [53]:
G.remove_nodes_from

In [56]:
G.edges
G.nodes

NodeView(('u1', 'u2', 'u3', 'u4'))

In [43]:
import torch
torch.manual_seed(2022)
x = torch.randperm(3)[:2]
y = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x.tolist()

[2, 1]

In [47]:
list(G.edges())

[(0, 1), (0, 1)]

In [45]:
y[x.tolist()]

tensor([[7, 8, 9],
        [4, 5, 6]])

In [1]:
with open("./data/FB15k-237/test.txt") as f:
    for line in f:
        u,r,v = line.strip().split("\t")
        print(u,r,v)
        break

/m/08966 /travel/travel_destination/climate./travel/travel_destination_monthly_climate/month /m/05lf_
